import { Cabin } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const cabin = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Sportstr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className={cabin.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
